# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PlainTextEdit import mPlainTextEdit
from PromptText import MyTextEditor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1201, 714)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 674))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* 원하는 색상으로 변경 */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_split_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_split_btn.sizePolicy().hasHeightForWidth())
        self.left_split_btn.setSizePolicy(sizePolicy)
        self.left_split_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.left_split_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.left_split_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.left_split_btn.setObjectName("left_split_btn")
        self.horizontalLayout_3.addWidget(self.left_split_btn)
        spacerItem = QtWidgets.QSpacerItem(68, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.right_split_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_split_btn.sizePolicy().hasHeightForWidth())
        self.right_split_btn.setSizePolicy(sizePolicy)
        self.right_split_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.right_split_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.right_split_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.right_split_btn.setObjectName("right_split_btn")
        self.horizontalLayout_3.addWidget(self.right_split_btn)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 30)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.new_chat_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_chat_btn.sizePolicy().hasHeightForWidth())
        self.new_chat_btn.setSizePolicy(sizePolicy)
        self.new_chat_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.new_chat_btn.setMaximumSize(QtCore.QSize(21, 21))
        self.new_chat_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.new_chat_btn.setObjectName("new_chat_btn")
        self.horizontalLayout_2.addWidget(self.new_chat_btn)
        self.del_chat_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_chat_btn.sizePolicy().hasHeightForWidth())
        self.del_chat_btn.setSizePolicy(sizePolicy)
        self.del_chat_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.del_chat_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.del_chat_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.del_chat_btn.setObjectName("del_chat_btn")
        self.horizontalLayout_2.addWidget(self.del_chat_btn)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.chat_room_table = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_room_table.sizePolicy().hasHeightForWidth())
        self.chat_room_table.setSizePolicy(sizePolicy)
        self.chat_room_table.setMinimumSize(QtCore.QSize(0, 0))
        self.chat_room_table.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.chat_room_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chat_room_table.setStyleSheet("QTableWidget{\n"
"    color: rgb(166, 217, 171);\n"
"    border: 1px solid white;\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(40,40,40);\n"
"    color: rgb(166, 217, 171);\n"
"    border: 1px solid rgb(40,40,40); /* 드롭다운 목록 테두리 (선택 사항) */\n"
"    border-bottom: 1px solid rgb(166, 217, 171);\n"
"}\n"
"QTableWidget::item{\n"
"    border-top: 1px solid rgb(166, 217, 171);\n"
"    border-bottom: 1px solid rgb(166, 217, 171);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    color: white;\n"
"    background-color: rgb(0,70,0); /* 항목 선택 시 배경색 */\n"
"    border: 1px solid rgb(166, 217, 171); /* 드롭다운 목록 테두리 (선택 사항) */\n"
"}\n"
"/* QTableWidget 내에 생성되는 편집기 위젯(QLineEdit)의 스타일 */\n"
"QTableWidget QLineEdit {\n"
"    color: white;\n"
"}\n"
"QTableWidget:focus {    /*테이블 선택시 테두리 색깔*/\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"}")
        self.chat_room_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_room_table.setMidLineWidth(0)
        self.chat_room_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.chat_room_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.chat_room_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.chat_room_table.setObjectName("chat_room_table")
        self.chat_room_table.setColumnCount(1)
        self.chat_room_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.chat_room_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chat_room_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.chat_room_table.setItem(0, 0, item)
        self.chat_room_table.horizontalHeader().setVisible(True)
        self.chat_room_table.horizontalHeader().setCascadingSectionResizes(False)
        self.chat_room_table.horizontalHeader().setDefaultSectionSize(100)
        self.chat_room_table.horizontalHeader().setHighlightSections(True)
        self.chat_room_table.horizontalHeader().setSortIndicatorShown(False)
        self.chat_room_table.horizontalHeader().setStretchLastSection(True)
        self.chat_room_table.verticalHeader().setVisible(False)
        self.chat_room_table.verticalHeader().setCascadingSectionResizes(False)
        self.chat_room_table.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_3.addWidget(self.chat_room_table)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 26)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.non_history_txt = QtWidgets.QTextEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.non_history_txt.sizePolicy().hasHeightForWidth())
        self.non_history_txt.setSizePolicy(sizePolicy)
        self.non_history_txt.setMinimumSize(QtCore.QSize(300, 0))
        self.non_history_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.non_history_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.non_history_txt.setReadOnly(True)
        self.non_history_txt.setObjectName("non_history_txt")
        self.gridLayout.addWidget(self.non_history_txt, 1, 0, 1, 1)
        self.history_txt = QtWidgets.QTextEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_txt.sizePolicy().hasHeightForWidth())
        self.history_txt.setSizePolicy(sizePolicy)
        self.history_txt.setMinimumSize(QtCore.QSize(300, 0))
        self.history_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.history_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.history_txt.setReadOnly(True)
        self.history_txt.setObjectName("history_txt")
        self.gridLayout.addWidget(self.history_txt, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 22)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # self.input_text = QtWidgets.QPlainTextEdit(self.widget1)
        self.input_text = mPlainTextEdit(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_text.sizePolicy().hasHeightForWidth())
        self.input_text.setSizePolicy(sizePolicy)
        self.input_text.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_text.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.input_text.setPlainText("")
        self.input_text.setObjectName("input_text")
        self.horizontalLayout.addWidget(self.input_text)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(13, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(65, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(13, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.send_btn.setAutoDefault(False)
        self.send_btn.setFlat(False)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(65, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 8)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 3)
        self.gridLayout_2.setRowStretch(2, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.Setting = QtWidgets.QWidget()
        self.Setting.setObjectName("Setting")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Setting)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.Setting)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.api_key_txt = QtWidgets.QLineEdit(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.api_key_txt.sizePolicy().hasHeightForWidth())
        self.api_key_txt.setSizePolicy(sizePolicy)
        self.api_key_txt.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.api_key_txt.setText("")
        self.api_key_txt.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.api_key_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.api_key_txt.setObjectName("api_key_txt")
        self.verticalLayout_2.addWidget(self.api_key_txt)
        self.label_4 = QtWidgets.QLabel(self.Setting)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        # self.prompt_txt = QtWidgets.QTextEdit(self.Setting)
        self.prompt_txt = MyTextEditor(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prompt_txt.sizePolicy().hasHeightForWidth())
        self.prompt_txt.setSizePolicy(sizePolicy)
        self.prompt_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.prompt_txt.setObjectName("prompt_txt")
        self.verticalLayout_2.addWidget(self.prompt_txt)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.Setting)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.Setting)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.temp_val = QtWidgets.QLineEdit(self.Setting)
        self.temp_val.setMinimumSize(QtCore.QSize(30, 0))
        self.temp_val.setStyleSheet("QLineEdit {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.temp_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_val.setObjectName("temp_val")
        self.horizontalLayout_4.addWidget(self.temp_val)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.temp_slider = QtWidgets.QSlider(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_slider.sizePolicy().hasHeightForWidth())
        self.temp_slider.setSizePolicy(sizePolicy)
        self.temp_slider.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: rgb(166, 217, 171);\n"
"    width: 20px;\n"
"    margin: -5px 0;\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    background: rgb(100,170,100);\n"
"}\n"
"QSlider::handle:horizontal:pressed{\n"
"    background: rgb(50,120,50);\n"
"}")
        self.temp_slider.setMaximum(100)
        self.temp_slider.setSingleStep(1)
        self.temp_slider.setProperty("value", 0)
        self.temp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.temp_slider.setObjectName("temp_slider")
        self.verticalLayout_2.addWidget(self.temp_slider)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.Setting, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_5.addWidget(self.splitter)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1201, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Setting = QtWidgets.QMenu(self.menubar)
        self.menu_Setting.setObjectName("menu_Setting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menu_Setting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.send_btn.clicked.connect(self.input_text.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.send_btn, self.input_text)
        MainWindow.setTabOrder(self.input_text, self.non_history_txt)
        MainWindow.setTabOrder(self.non_history_txt, self.history_txt)
        MainWindow.setTabOrder(self.history_txt, self.tabWidget)

        self.input_text.set_send_button(self.send_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_split_btn.setText(_translate("MainWindow", "l<"))
        self.right_split_btn.setText(_translate("MainWindow", ">l"))
        self.new_chat_btn.setText(_translate("MainWindow", "+"))
        self.del_chat_btn.setText(_translate("MainWindow", "-"))
        item = self.chat_room_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.chat_room_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Chat Rooms"))
        __sortingEnabled = self.chat_room_table.isSortingEnabled()
        self.chat_room_table.setSortingEnabled(False)
        item = self.chat_room_table.item(0, 0)
        item.setText(_translate("MainWindow", "chat1"))
        self.chat_room_table.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "Default"))
        self.label_2.setText(_translate("MainWindow", "Experiment"))
        self.input_text.setPlaceholderText(_translate("MainWindow", "Enter your message..."))
        self.send_btn.setText(_translate("MainWindow", "send"))
        self.label_3.setText(_translate("MainWindow", "Api-key"))
        self.api_key_txt.setPlaceholderText(_translate("MainWindow", "Enter your api key..."))
        self.label_4.setText(_translate("MainWindow", "Prompt"))
        self.prompt_txt.setPlaceholderText(_translate("MainWindow", "Enter your prompt..."))
        self.label_5.setText(_translate("MainWindow", "Temperature"))
        self.temp_val.setText(_translate("MainWindow", "0.00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setting), _translate("MainWindow", "setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu_Setting.setTitle(_translate("MainWindow", "&Setting"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
