# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 739)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 674))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* 원하는 색상으로 변경 */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_split_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_split_btn.sizePolicy().hasHeightForWidth())
        self.left_split_btn.setSizePolicy(sizePolicy)
        self.left_split_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.left_split_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.left_split_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.left_split_btn.setObjectName("left_split_btn")
        self.horizontalLayout_3.addWidget(self.left_split_btn)
        spacerItem = QtWidgets.QSpacerItem(68, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.right_split_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_split_btn.sizePolicy().hasHeightForWidth())
        self.right_split_btn.setSizePolicy(sizePolicy)
        self.right_split_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.right_split_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.right_split_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.right_split_btn.setObjectName("right_split_btn")
        self.horizontalLayout_3.addWidget(self.right_split_btn)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 30)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(0, 18, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.new_chat_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_chat_btn.sizePolicy().hasHeightForWidth())
        self.new_chat_btn.setSizePolicy(sizePolicy)
        self.new_chat_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.new_chat_btn.setMaximumSize(QtCore.QSize(21, 21))
        self.new_chat_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.new_chat_btn.setObjectName("new_chat_btn")
        self.horizontalLayout_2.addWidget(self.new_chat_btn)
        self.del_chat_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.del_chat_btn.sizePolicy().hasHeightForWidth())
        self.del_chat_btn.setSizePolicy(sizePolicy)
        self.del_chat_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.del_chat_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.del_chat_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.del_chat_btn.setObjectName("del_chat_btn")
        self.horizontalLayout_2.addWidget(self.del_chat_btn)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 10)
        self.horizontalLayout_2.setStretch(2, 10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.chat_room_table = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chat_room_table.sizePolicy().hasHeightForWidth())
        self.chat_room_table.setSizePolicy(sizePolicy)
        self.chat_room_table.setMinimumSize(QtCore.QSize(0, 0))
        self.chat_room_table.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.chat_room_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chat_room_table.setStyleSheet("QTableWidget{\n"
"    color: rgb(166, 217, 171);\n"
"    border: 1px solid white;\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(40,40,40);\n"
"    color: rgb(166, 217, 171);\n"
"    border: 1px solid rgb(40,40,40); /* 드롭다운 목록 테두리 (선택 사항) */\n"
"    border-bottom: 1px solid rgb(166, 217, 171);\n"
"}\n"
"QTableWidget::item{\n"
"    border-top: 1px solid rgb(166, 217, 171);\n"
"    border-bottom: 1px solid rgb(166, 217, 171);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    color: white;\n"
"    background-color: rgb(0,70,0); /* 항목 선택 시 배경색 */\n"
"    border: 1px solid rgb(166, 217, 171); /* 드롭다운 목록 테두리 (선택 사항) */\n"
"}\n"
"/* QTableWidget 내에 생성되는 편집기 위젯(QLineEdit)의 스타일 */\n"
"QTableWidget QLineEdit {\n"
"    color: white;\n"
"}\n"
"QTableWidget:focus {    /*테이블 선택시 테두리 색깔*/\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"}")
        self.chat_room_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_room_table.setMidLineWidth(0)
        self.chat_room_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.chat_room_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.chat_room_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.chat_room_table.setObjectName("chat_room_table")
        self.chat_room_table.setColumnCount(1)
        self.chat_room_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.chat_room_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chat_room_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.chat_room_table.setItem(0, 0, item)
        self.chat_room_table.horizontalHeader().setVisible(True)
        self.chat_room_table.horizontalHeader().setCascadingSectionResizes(False)
        self.chat_room_table.horizontalHeader().setDefaultSectionSize(100)
        self.chat_room_table.horizontalHeader().setHighlightSections(True)
        self.chat_room_table.horizontalHeader().setSortIndicatorShown(False)
        self.chat_room_table.horizontalHeader().setStretchLastSection(True)
        self.chat_room_table.verticalHeader().setVisible(False)
        self.chat_room_table.verticalHeader().setCascadingSectionResizes(False)
        self.chat_room_table.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_3.addWidget(self.chat_room_table)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 26)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.default_token_bar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.default_token_bar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(50, 120, 50), stop:1 rgb(100,180,100));\n"
"    border-radius: 2px;\n"
"}")
        self.default_token_bar.setProperty("value", 20)
        self.default_token_bar.setObjectName("default_token_bar")
        self.horizontalLayout_7.addWidget(self.default_token_bar)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.default_txt = QtWidgets.QTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.default_txt.sizePolicy().hasHeightForWidth())
        self.default_txt.setSizePolicy(sizePolicy)
        self.default_txt.setMinimumSize(QtCore.QSize(300, 0))
        self.default_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.default_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.default_txt.setReadOnly(True)
        self.default_txt.setObjectName("default_txt")
        self.verticalLayout.addWidget(self.default_txt)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.experiment_token_bar = QtWidgets.QProgressBar(self.layoutWidget1)
        self.experiment_token_bar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(50, 120, 50), stop:1 rgb(100,180,100));\n"
"    border-radius: 2px;\n"
"}")
        self.experiment_token_bar.setProperty("value", 0)
        self.experiment_token_bar.setObjectName("experiment_token_bar")
        self.horizontalLayout_8.addWidget(self.experiment_token_bar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.experiment_txt = QtWidgets.QTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.experiment_txt.sizePolicy().hasHeightForWidth())
        self.experiment_txt.setSizePolicy(sizePolicy)
        self.experiment_txt.setMinimumSize(QtCore.QSize(300, 0))
        self.experiment_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.experiment_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.experiment_txt.setReadOnly(True)
        self.experiment_txt.setObjectName("experiment_txt")
        self.verticalLayout_5.addWidget(self.experiment_txt)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_text = QtWidgets.QPlainTextEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_text.sizePolicy().hasHeightForWidth())
        self.input_text.setSizePolicy(sizePolicy)
        self.input_text.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_text.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.input_text.setPlainText("")
        self.input_text.setObjectName("input_text")
        self.horizontalLayout.addWidget(self.input_text)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(65, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 1, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.send_btn.setAutoDefault(False)
        self.send_btn.setFlat(False)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(65, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(13, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(13, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 8)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 3)
        self.gridLayout_2.setRowStretch(2, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_7.setStretch(0, 7)
        self.verticalLayout_7.setStretch(1, 2)
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.Setting = QtWidgets.QWidget()
        self.Setting.setObjectName("Setting")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Setting)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.Setting)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.api_key_txt = QtWidgets.QLineEdit(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.api_key_txt.sizePolicy().hasHeightForWidth())
        self.api_key_txt.setSizePolicy(sizePolicy)
        self.api_key_txt.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.api_key_txt.setText("")
        self.api_key_txt.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.api_key_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.api_key_txt.setObjectName("api_key_txt")
        self.verticalLayout_2.addWidget(self.api_key_txt)
        self.label_4 = QtWidgets.QLabel(self.Setting)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.prompt_txt = QtWidgets.QTextEdit(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prompt_txt.sizePolicy().hasHeightForWidth())
        self.prompt_txt.setSizePolicy(sizePolicy)
        self.prompt_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.prompt_txt.setObjectName("prompt_txt")
        self.verticalLayout_2.addWidget(self.prompt_txt)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.Setting)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.temp_val = QtWidgets.QLineEdit(self.Setting)
        self.temp_val.setMinimumSize(QtCore.QSize(30, 0))
        self.temp_val.setStyleSheet("QLineEdit {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.temp_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_val.setObjectName("temp_val")
        self.horizontalLayout_4.addWidget(self.temp_val)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.temp_slider = QtWidgets.QSlider(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_slider.sizePolicy().hasHeightForWidth())
        self.temp_slider.setSizePolicy(sizePolicy)
        self.temp_slider.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: rgb(166, 217, 171);\n"
"    width: 20px;\n"
"    margin: -5px 0;\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    background: rgb(100,170,100);\n"
"}\n"
"QSlider::handle:horizontal:pressed{\n"
"    background: rgb(50,120,50);\n"
"}")
        self.temp_slider.setMaximum(100)
        self.temp_slider.setSingleStep(1)
        self.temp_slider.setProperty("value", 0)
        self.temp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.temp_slider.setObjectName("temp_slider")
        self.verticalLayout_2.addWidget(self.temp_slider)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.Setting, "")
        self.RAG = QtWidgets.QWidget()
        self.RAG.setObjectName("RAG")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.RAG)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_6 = QtWidgets.QGroupBox(self.RAG)
        self.groupBox_6.setStyleSheet("QGroupBox {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_13.setContentsMargins(9, 3, 9, 3)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem10)
        self.widget_2 = QtWidgets.QWidget(self.groupBox_6)
        self.widget_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem11)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_20.addWidget(self.label_14)
        self.rag_transformation = QtWidgets.QLabel(self.widget_2)
        self.rag_transformation.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.rag_transformation.setObjectName("rag_transformation")
        self.horizontalLayout_20.addWidget(self.rag_transformation)
        self.verticalLayout_13.addWidget(self.widget_2)
        self.default_generator = QtWidgets.QRadioButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.default_generator.sizePolicy().hasHeightForWidth())
        self.default_generator.setSizePolicy(sizePolicy)
        self.default_generator.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.default_generator.setObjectName("default_generator")
        self.verticalLayout_13.addWidget(self.default_generator)
        self.rewrite_generator = QtWidgets.QRadioButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rewrite_generator.sizePolicy().hasHeightForWidth())
        self.rewrite_generator.setSizePolicy(sizePolicy)
        self.rewrite_generator.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.rewrite_generator.setObjectName("rewrite_generator")
        self.verticalLayout_13.addWidget(self.rewrite_generator)
        self.multiple_generator = QtWidgets.QRadioButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiple_generator.sizePolicy().hasHeightForWidth())
        self.multiple_generator.setSizePolicy(sizePolicy)
        self.multiple_generator.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.multiple_generator.setObjectName("multiple_generator")
        self.verticalLayout_13.addWidget(self.multiple_generator)
        self.step_back_generator = QtWidgets.QRadioButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_back_generator.sizePolicy().hasHeightForWidth())
        self.step_back_generator.setSizePolicy(sizePolicy)
        self.step_back_generator.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.step_back_generator.setObjectName("step_back_generator")
        self.verticalLayout_13.addWidget(self.step_back_generator)
        self.verticalLayout_13.setStretch(0, 1)
        self.verticalLayout_13.setStretch(1, 1)
        self.verticalLayout_13.setStretch(2, 3)
        self.verticalLayout_13.setStretch(3, 3)
        self.verticalLayout_13.setStretch(4, 3)
        self.verticalLayout_13.setStretch(5, 3)
        self.verticalLayout_16.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.RAG)
        self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.widget_3.setStyleSheet("QWidget{\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        self.rag_indexing = QtWidgets.QLabel(self.widget_3)
        self.rag_indexing.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.rag_indexing.setObjectName("rag_indexing")
        self.horizontalLayout_17.addWidget(self.rag_indexing)
        self.verticalLayout_12.addWidget(self.widget_3)
        self.default_retriever = QtWidgets.QRadioButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.default_retriever.sizePolicy().hasHeightForWidth())
        self.default_retriever.setSizePolicy(sizePolicy)
        self.default_retriever.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.default_retriever.setObjectName("default_retriever")
        self.verticalLayout_12.addWidget(self.default_retriever)
        self.parent_retriever = QtWidgets.QRadioButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parent_retriever.sizePolicy().hasHeightForWidth())
        self.parent_retriever.setSizePolicy(sizePolicy)
        self.parent_retriever.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.parent_retriever.setObjectName("parent_retriever")
        self.verticalLayout_12.addWidget(self.parent_retriever)
        self.widget_4 = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("QWidget {\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem14)
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.parentretreiver_parent_chunk_size = QtWidgets.QSpinBox(self.groupBox)
        self.parentretreiver_parent_chunk_size.setStyleSheet("QSpinBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.parentretreiver_parent_chunk_size.setMaximum(100000)
        self.parentretreiver_parent_chunk_size.setSingleStep(10)
        self.parentretreiver_parent_chunk_size.setObjectName("parentretreiver_parent_chunk_size")
        self.horizontalLayout_11.addWidget(self.parentretreiver_parent_chunk_size)
        self.horizontalLayout_11.setStretch(0, 6)
        self.horizontalLayout_11.setStretch(1, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.parentretreiver_child_chunk_size = QtWidgets.QSpinBox(self.groupBox)
        self.parentretreiver_child_chunk_size.setStyleSheet("QSpinBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.parentretreiver_child_chunk_size.setMaximum(100000)
        self.parentretreiver_child_chunk_size.setSingleStep(10)
        self.parentretreiver_child_chunk_size.setObjectName("parentretreiver_child_chunk_size")
        self.horizontalLayout_12.addWidget(self.parentretreiver_child_chunk_size)
        self.horizontalLayout_12.setStretch(0, 6)
        self.horizontalLayout_12.setStretch(1, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 19)
        self.verticalLayout_12.addWidget(self.widget_4)
        self.summary_retriever = QtWidgets.QRadioButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summary_retriever.sizePolicy().hasHeightForWidth())
        self.summary_retriever.setSizePolicy(sizePolicy)
        self.summary_retriever.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.summary_retriever.setObjectName("summary_retriever")
        self.verticalLayout_12.addWidget(self.summary_retriever)
        self.widget_5 = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_5)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_14.addWidget(self.label_10)
        self.summary_parent_chunk_size = QtWidgets.QSpinBox(self.groupBox_2)
        self.summary_parent_chunk_size.setStyleSheet("QSpinBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.summary_parent_chunk_size.setMaximum(100000)
        self.summary_parent_chunk_size.setSingleStep(10)
        self.summary_parent_chunk_size.setObjectName("summary_parent_chunk_size")
        self.horizontalLayout_14.addWidget(self.summary_parent_chunk_size)
        self.horizontalLayout_14.setStretch(0, 6)
        self.horizontalLayout_14.setStretch(1, 3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13.addWidget(self.groupBox_2)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 19)
        self.verticalLayout_12.addWidget(self.widget_5)
        self.hypothetical_retriever = QtWidgets.QRadioButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hypothetical_retriever.sizePolicy().hasHeightForWidth())
        self.hypothetical_retriever.setSizePolicy(sizePolicy)
        self.hypothetical_retriever.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.hypothetical_retriever.setObjectName("hypothetical_retriever")
        self.verticalLayout_12.addWidget(self.hypothetical_retriever)
        self.widget_6 = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("QWidget {\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem16)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_6)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.hypo_parent_chunk_size = QtWidgets.QSpinBox(self.groupBox_3)
        self.hypo_parent_chunk_size.setStyleSheet("QSpinBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.hypo_parent_chunk_size.setMaximum(100000)
        self.hypo_parent_chunk_size.setSingleStep(10)
        self.hypo_parent_chunk_size.setObjectName("hypo_parent_chunk_size")
        self.horizontalLayout_16.addWidget(self.hypo_parent_chunk_size)
        self.horizontalLayout_16.setStretch(0, 6)
        self.horizontalLayout_16.setStretch(1, 3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_15.addWidget(self.groupBox_3)
        self.horizontalLayout_15.setStretch(0, 1)
        self.horizontalLayout_15.setStretch(1, 19)
        self.verticalLayout_12.addWidget(self.widget_6)
        self.granular_retriever = QtWidgets.QRadioButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.granular_retriever.sizePolicy().hasHeightForWidth())
        self.granular_retriever.setSizePolicy(sizePolicy)
        self.granular_retriever.setStyleSheet("QRadioButton {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.granular_retriever.setObjectName("granular_retriever")
        self.verticalLayout_12.addWidget(self.granular_retriever)
        self.widget_7 = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem17)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_7)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_19.addWidget(self.label_13)
        self.granular_chunk_size = QtWidgets.QSpinBox(self.groupBox_4)
        self.granular_chunk_size.setStyleSheet("QSpinBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.granular_chunk_size.setMaximum(100000)
        self.granular_chunk_size.setSingleStep(10)
        self.granular_chunk_size.setObjectName("granular_chunk_size")
        self.horizontalLayout_19.addWidget(self.granular_chunk_size)
        self.horizontalLayout_19.setStretch(0, 6)
        self.horizontalLayout_19.setStretch(1, 3)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_18.addWidget(self.groupBox_4)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 19)
        self.verticalLayout_12.addWidget(self.widget_7)
        self.verticalLayout_12.setStretch(0, 2)
        self.verticalLayout_12.setStretch(1, 1)
        self.verticalLayout_12.setStretch(2, 3)
        self.verticalLayout_12.setStretch(3, 3)
        self.verticalLayout_12.setStretch(4, 3)
        self.verticalLayout_12.setStretch(5, 3)
        self.verticalLayout_12.setStretch(6, 3)
        self.verticalLayout_12.setStretch(7, 3)
        self.verticalLayout_12.setStretch(8, 3)
        self.verticalLayout_12.setStretch(9, 3)
        self.verticalLayout_12.setStretch(10, 3)
        self.verticalLayout_16.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.RAG)
        self.groupBox_7.setStyleSheet("QGroupBox {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_15.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem18)
        self.widget_8 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_8.setStyleSheet("QWidget{\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem19)
        self.label_15 = QtWidgets.QLabel(self.widget_8)
        self.label_15.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.rag_post_processing = QtWidgets.QLabel(self.widget_8)
        self.rag_post_processing.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.rag_post_processing.setObjectName("rag_post_processing")
        self.horizontalLayout_21.addWidget(self.rag_post_processing)
        self.verticalLayout_15.addWidget(self.widget_8)
        self.widget_10 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_10.setStyleSheet("QWidget {\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.similarity_post_processor = QtWidgets.QCheckBox(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.similarity_post_processor.sizePolicy().hasHeightForWidth())
        self.similarity_post_processor.setSizePolicy(sizePolicy)
        self.similarity_post_processor.setStyleSheet("QCheckBox {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.similarity_post_processor.setObjectName("similarity_post_processor")
        self.horizontalLayout_24.addWidget(self.similarity_post_processor)
        spacerItem20 = QtWidgets.QSpacerItem(78, 13, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem20)
        self.similarity_val = QtWidgets.QLineEdit(self.widget_10)
        self.similarity_val.setMinimumSize(QtCore.QSize(30, 0))
        self.similarity_val.setStyleSheet("QLineEdit {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.similarity_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.similarity_val.setObjectName("similarity_val")
        self.horizontalLayout_24.addWidget(self.similarity_val)
        self.horizontalLayout_24.setStretch(0, 3)
        self.horizontalLayout_24.setStretch(1, 3)
        self.horizontalLayout_24.setStretch(2, 1)
        self.verticalLayout_15.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_11.setStyleSheet("QWidget {\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem21)
        self.similarity_slider = QtWidgets.QSlider(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.similarity_slider.sizePolicy().hasHeightForWidth())
        self.similarity_slider.setSizePolicy(sizePolicy)
        self.similarity_slider.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: rgb(166, 217, 171);\n"
"    width: 20px;\n"
"    margin: -5px 0;\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    background: rgb(100,170,100);\n"
"}\n"
"QSlider::handle:horizontal:pressed{\n"
"    background: rgb(50,120,50);\n"
"}")
        self.similarity_slider.setMaximum(100)
        self.similarity_slider.setSingleStep(1)
        self.similarity_slider.setProperty("value", 0)
        self.similarity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.similarity_slider.setObjectName("similarity_slider")
        self.horizontalLayout_25.addWidget(self.similarity_slider)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 19)
        self.verticalLayout_15.addWidget(self.widget_11)
        self.keywords = QtWidgets.QCheckBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keywords.sizePolicy().hasHeightForWidth())
        self.keywords.setSizePolicy(sizePolicy)
        self.keywords.setStyleSheet("QCheckBox {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.keywords.setObjectName("keywords")
        self.verticalLayout_15.addWidget(self.keywords)
        self.widget_9 = QtWidgets.QWidget(self.groupBox_7)
        self.widget_9.setStyleSheet("QWidget {\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem22)
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget_9)
        self.groupBox_8.setStyleSheet("QGroupBox {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40);\n"
"}")
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_23.addWidget(self.label_16)
        self.keyword_txt = QtWidgets.QLineEdit(self.groupBox_8)
        self.keyword_txt.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.keyword_txt.setObjectName("keyword_txt")
        self.horizontalLayout_23.addWidget(self.keyword_txt)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22.addWidget(self.groupBox_8)
        self.horizontalLayout_22.setStretch(0, 1)
        self.horizontalLayout_22.setStretch(1, 19)
        self.verticalLayout_15.addWidget(self.widget_9)
        self.reciprocal_rank_fusion = QtWidgets.QCheckBox(self.groupBox_7)
        self.reciprocal_rank_fusion.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reciprocal_rank_fusion.sizePolicy().hasHeightForWidth())
        self.reciprocal_rank_fusion.setSizePolicy(sizePolicy)
        self.reciprocal_rank_fusion.setStyleSheet("QCheckBox {\n"
"    color: rgb(166, 217, 171);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}")
        self.reciprocal_rank_fusion.setCheckable(True)
        self.reciprocal_rank_fusion.setChecked(False)
        self.reciprocal_rank_fusion.setObjectName("reciprocal_rank_fusion")
        self.verticalLayout_15.addWidget(self.reciprocal_rank_fusion)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_15.setStretch(2, 3)
        self.verticalLayout_15.setStretch(3, 3)
        self.verticalLayout_15.setStretch(4, 3)
        self.verticalLayout_15.setStretch(5, 3)
        self.verticalLayout_16.addWidget(self.groupBox_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.RAG)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.path = QtWidgets.QLabel(self.RAG)
        self.path.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.path.setText("")
        self.path.setObjectName("path")
        self.horizontalLayout_5.addWidget(self.path)
        self.Load_btn = QtWidgets.QPushButton(self.RAG)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Load_btn.sizePolicy().hasHeightForWidth())
        self.Load_btn.setSizePolicy(sizePolicy)
        self.Load_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.Load_btn.setAutoDefault(False)
        self.Load_btn.setFlat(False)
        self.Load_btn.setObjectName("Load_btn")
        self.horizontalLayout_5.addWidget(self.Load_btn)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 6)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.RAG)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.Loading_bar = QtWidgets.QProgressBar(self.RAG)
        self.Loading_bar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(40, 40, 40);\n"
"    text-align: center;\n"
"    color: White;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgb(50, 120, 50), stop:1 rgb(100,180,100));\n"
"    border-radius: 2px;\n"
"}")
        self.Loading_bar.setProperty("value", 0)
        self.Loading_bar.setObjectName("Loading_bar")
        self.horizontalLayout_6.addWidget(self.Loading_bar)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 4)
        self.verticalLayout_16.addLayout(self.horizontalLayout_6)
        spacerItem23 = QtWidgets.QSpacerItem(236, 34, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem23)
        self.tabWidget.addTab(self.RAG, "")
        self.verticalLayout_8.addWidget(self.splitter)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 30)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Setting = QtWidgets.QMenu(self.menubar)
        self.menu_Setting.setObjectName("menu_Setting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menu_Setting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.send_btn.clicked.connect(self.input_text.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.send_btn, self.input_text)
        MainWindow.setTabOrder(self.input_text, self.default_txt)
        MainWindow.setTabOrder(self.default_txt, self.experiment_txt)
        MainWindow.setTabOrder(self.experiment_txt, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_split_btn.setText(_translate("MainWindow", "l<"))
        self.right_split_btn.setText(_translate("MainWindow", ">l"))
        self.new_chat_btn.setText(_translate("MainWindow", "+"))
        self.del_chat_btn.setText(_translate("MainWindow", "-"))
        item = self.chat_room_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.chat_room_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Chat Rooms"))
        __sortingEnabled = self.chat_room_table.isSortingEnabled()
        self.chat_room_table.setSortingEnabled(False)
        item = self.chat_room_table.item(0, 0)
        item.setText(_translate("MainWindow", "chat1"))
        self.chat_room_table.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "DEFAULT"))
        self.default_token_bar.setFormat(_translate("MainWindow", "used tokens: %p%"))
        self.label_2.setText(_translate("MainWindow", "EXPERIMENT"))
        self.experiment_token_bar.setFormat(_translate("MainWindow", "used tokens: %p%"))
        self.input_text.setPlaceholderText(_translate("MainWindow", "Enter your message..."))
        self.send_btn.setText(_translate("MainWindow", "send"))
        self.label_3.setText(_translate("MainWindow", "Api-key"))
        self.api_key_txt.setPlaceholderText(_translate("MainWindow", "Enter your api key..."))
        self.label_4.setText(_translate("MainWindow", "Prompt"))
        self.prompt_txt.setPlaceholderText(_translate("MainWindow", "Enter your prompt..."))
        self.label_5.setText(_translate("MainWindow", "Temperature"))
        self.temp_val.setText(_translate("MainWindow", "0.00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setting), _translate("MainWindow", "setting"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Question Transformations"))
        self.label_14.setText(_translate("MainWindow", "Applied: "))
        self.rag_transformation.setText(_translate("MainWindow", "TextLabel"))
        self.default_generator.setText(_translate("MainWindow", "Default"))
        self.rewrite_generator.setText(_translate("MainWindow", "Rewrite-Retrieve-Read Generator"))
        self.multiple_generator.setText(_translate("MainWindow", "Multiple Questions Generator"))
        self.step_back_generator.setText(_translate("MainWindow", "Step-Back Question Generator"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Advanced Indexing"))
        self.label_12.setText(_translate("MainWindow", "Applied: "))
        self.rag_indexing.setText(_translate("MainWindow", "TextLabel"))
        self.default_retriever.setText(_translate("MainWindow", "Default"))
        self.parent_retriever.setText(_translate("MainWindow", "ParentRetriverPipeline"))
        self.label_8.setText(_translate("MainWindow", "parent_chunk_size:"))
        self.label_9.setText(_translate("MainWindow", "child_chunk_size:"))
        self.summary_retriever.setText(_translate("MainWindow", "Summary"))
        self.label_10.setText(_translate("MainWindow", "parent_chunk_size:"))
        self.hypothetical_retriever.setText(_translate("MainWindow", "Hypothetical"))
        self.label_11.setText(_translate("MainWindow", "parent_chunk_size:"))
        self.granular_retriever.setText(_translate("MainWindow", "Granular"))
        self.label_13.setText(_translate("MainWindow", "chunk_size:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Retrieval Post-Processing"))
        self.label_15.setText(_translate("MainWindow", "Applied: "))
        self.rag_post_processing.setText(_translate("MainWindow", "TextLabel"))
        self.similarity_post_processor.setText(_translate("MainWindow", "Similarity post-processor"))
        self.similarity_val.setText(_translate("MainWindow", "0.00"))
        self.keywords.setText(_translate("MainWindow", "Keywords"))
        self.label_16.setText(_translate("MainWindow", "keywords"))
        self.reciprocal_rank_fusion.setToolTip(_translate("MainWindow", "only Multiple Questions Generator can use this function"))
        self.reciprocal_rank_fusion.setText(_translate("MainWindow", "Reciprocal Rank Fusion"))
        self.label_6.setText(_translate("MainWindow", "Path: "))
        self.Load_btn.setText(_translate("MainWindow", "Load"))
        self.label_7.setText(_translate("MainWindow", "Loading"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RAG), _translate("MainWindow", "RAG"))
        self.menu_Setting.setTitle(_translate("MainWindow", "&Setting"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
