# Form implementation generated from reading ui file '.\ui\Server.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QHeaderView, QTableWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 653)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* 원하는 색상으로 변경 */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_start = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.btn_start.setAutoDefault(False)
        self.btn_start.setFlat(False)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop.sizePolicy().hasHeightForWidth())
        self.btn_stop.setSizePolicy(sizePolicy)
        self.btn_stop.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.btn_stop.setAutoDefault(False)
        self.btn_stop.setFlat(False)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.client_table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.client_table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        self.client_table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.client_table.setStyleSheet("QTableWidget{\n"
"    color: rgb(166, 217, 171);\n"
"    border: 1px solid white;\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(40,40,40);\n"
"    color: rgb(166, 217, 171);\n"
"    border: 1px solid rgb(40,40,40); /* 드롭다운 목록 테두리 (선택 사항) */\n"
"    border-bottom: 1px solid rgb(166, 217, 171);\n"
"}\n"
"QTableWidget::item{\n"
"    border-top: 1px solid rgb(166, 217, 171);\n"
"    border-bottom: 1px solid rgb(166, 217, 171);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    color: white;\n"
"    background-color: rgb(0,70,0); /* 항목 선택 시 배경색 */\n"
"    border: 1px solid rgb(166, 217, 171); /* 드롭다운 목록 테두리 (선택 사항) */\n"
"}\n"
"/* QTableWidget 내에 생성되는 편집기 위젯(QLineEdit)의 스타일 */\n"
"QTableWidget QLineEdit {\n"
"    color: white;\n"
"}\n"
"QTableWidget:focus {    /*테이블 선택시 테두리 색깔*/\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"}")
        self.client_table.setRowCount(0)
        self.client_table.setObjectName("client_table")
        self.client_table.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.client_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_table.setHorizontalHeaderItem(1, item)
        self.client_table.horizontalHeader().setCascadingSectionResizes(False)
        self.client_table.horizontalHeader().setMinimumSectionSize(23)
        self.client_table.horizontalHeader().setSortIndicatorShown(False)
        self.client_table.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.client_table)
        self.btn_disconnect = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_disconnect.sizePolicy().hasHeightForWidth())
        self.btn_disconnect.setSizePolicy(sizePolicy)
        self.btn_disconnect.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.btn_disconnect.setAutoDefault(False)
        self.btn_disconnect.setFlat(False)
        self.btn_disconnect.setObjectName("btn_disconnect")
        self.verticalLayout.addWidget(self.btn_disconnect)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.log_browser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_browser.sizePolicy().hasHeightForWidth())
        self.log_browser.setSizePolicy(sizePolicy)
        self.log_browser.setMinimumSize(QtCore.QSize(0, 0))
        self.log_browser.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.log_browser.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhMultiLine)
        self.log_browser.setReadOnly(True)
        self.log_browser.setObjectName("log_browser")
        self.verticalLayout.addWidget(self.log_browser)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.msg_edit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg_edit.sizePolicy().hasHeightForWidth())
        self.msg_edit.setSizePolicy(sizePolicy)
        self.msg_edit.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.msg_edit.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.msg_edit.setPlainText("")
        self.msg_edit.setObjectName("msg_edit")
        self.verticalLayout.addWidget(self.msg_edit)
        self.btn_send = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send.sizePolicy().hasHeightForWidth())
        self.btn_send.setSizePolicy(sizePolicy)
        self.btn_send.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.btn_send.setAutoDefault(False)
        self.btn_send.setFlat(False)
        self.btn_send.setObjectName("btn_send")
        self.verticalLayout.addWidget(self.btn_send)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 7)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 7)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 4)
        self.verticalLayout.setStretch(7, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 33))
        self.menubar.setObjectName("menubar")
        self.menu_Setting = QtWidgets.QMenu(parent=self.menubar)
        self.menu_Setting.setObjectName("menu_Setting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menu_Setting.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_send.clicked.connect(self.msg_edit.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_send, self.msg_edit)
        MainWindow.setTabOrder(self.msg_edit, self.log_browser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start.setText(_translate("MainWindow", "서버 시작"))
        self.btn_stop.setText(_translate("MainWindow", "서버 종료"))
        item = self.client_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client IP Address"))
        item = self.client_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.btn_disconnect.setText(_translate("MainWindow", "선택한 클라이언트 강제 접속 해제"))
        self.label.setText(_translate("MainWindow", "수신된 로그"))
        self.label_2.setText(_translate("MainWindow", "클라이언트로 전송할 메세지:"))
        self.msg_edit.setPlaceholderText(_translate("MainWindow", "Enter your message..."))
        self.btn_send.setText(_translate("MainWindow", "send"))
        self.menu_Setting.setTitle(_translate("MainWindow", "&Setting"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
