# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#추가되는 include
from PlainTextEdit import mPlainTextEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 468)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.output_text = QtWidgets.QTextEdit(self.centralwidget)
        self.output_text.setObjectName("output_text")
        self.gridLayout.addWidget(self.output_text, 0, 0, 1, 2)
        #self.input_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input_text = mPlainTextEdit(self.centralwidget)
        self.input_text.setPlainText("")
        self.input_text.setObjectName("input_text")
        self.gridLayout.addWidget(self.input_text, 1, 0, 2, 1)
        self.setting_btn = QtWidgets.QPushButton(self.centralwidget)
        self.setting_btn.setEnabled(True)
        self.setting_btn.setObjectName("setting_btn")
        self.gridLayout.addWidget(self.setting_btn, 1, 1, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout.addWidget(self.send_btn, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Setting = QtWidgets.QMenu(self.menubar)
        self.menu_Setting.setObjectName("menu_Setting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_Setting.menuAction())

        self.retranslateUi(MainWindow)
        self.send_btn.clicked.connect(self.input_text.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #추가되는 코드
        self.input_text.set_send_button(self.send_btn)
        self.input_text.setPlaceholderText("Enter your message...")
        self.output_text.setReadOnly(True) #출력창 편집 방지

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.setting_btn.setText(_translate("MainWindow", "setting"))
        self.send_btn.setText(_translate("MainWindow", "send"))
        self.menu_Setting.setTitle(_translate("MainWindow", "&Setting"))
