# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 763)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 674))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* 원하는 색상으로 변경 */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.research_txt = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.research_txt.sizePolicy().hasHeightForWidth())
        self.research_txt.setSizePolicy(sizePolicy)
        self.research_txt.setMinimumSize(QtCore.QSize(300, 0))
        self.research_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.research_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.research_txt.setReadOnly(True)
        self.research_txt.setObjectName("research_txt")
        self.verticalLayout.addWidget(self.research_txt)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_txt.sizePolicy().hasHeightForWidth())
        self.input_txt.setSizePolicy(sizePolicy)
        self.input_txt.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.input_txt.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.input_txt.setPlainText("")
        self.input_txt.setObjectName("input_txt")
        self.horizontalLayout.addWidget(self.input_txt)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(13, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(65, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(13, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.send_btn.sizePolicy().hasHeightForWidth())
        self.send_btn.setSizePolicy(sizePolicy)
        self.send_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.send_btn.setAutoDefault(False)
        self.send_btn.setFlat(False)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(65, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 8)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 3)
        self.gridLayout_2.setRowStretch(2, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(0, 4)
        self.verticalLayout_3.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.Setting = QtWidgets.QWidget()
        self.Setting.setObjectName("Setting")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Setting)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.Setting)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.api_key_txt = QtWidgets.QLineEdit(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.api_key_txt.sizePolicy().hasHeightForWidth())
        self.api_key_txt.setSizePolicy(sizePolicy)
        self.api_key_txt.setStyleSheet("QLineEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.api_key_txt.setText("")
        self.api_key_txt.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.api_key_txt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.api_key_txt.setObjectName("api_key_txt")
        self.verticalLayout_2.addWidget(self.api_key_txt)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.Setting)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.Setting)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.query_val = QtWidgets.QLineEdit(self.Setting)
        self.query_val.setMinimumSize(QtCore.QSize(30, 0))
        self.query_val.setStyleSheet("QLineEdit {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.query_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.query_val.setObjectName("query_val")
        self.horizontalLayout_4.addWidget(self.query_val)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.query_num_slider = QtWidgets.QSlider(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_num_slider.sizePolicy().hasHeightForWidth())
        self.query_num_slider.setSizePolicy(sizePolicy)
        self.query_num_slider.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: rgb(166, 217, 171);\n"
"    width: 20px;\n"
"    margin: -5px 0;\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    background: rgb(100,170,100);\n"
"}\n"
"QSlider::handle:horizontal:pressed{\n"
"    background: rgb(50,120,50);\n"
"}")
        self.query_num_slider.setMinimum(1)
        self.query_num_slider.setMaximum(100)
        self.query_num_slider.setSingleStep(1)
        self.query_num_slider.setProperty("value", 1)
        self.query_num_slider.setOrientation(QtCore.Qt.Horizontal)
        self.query_num_slider.setObjectName("query_num_slider")
        self.verticalLayout_2.addWidget(self.query_num_slider)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.Setting)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.line_2 = QtWidgets.QFrame(self.Setting)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_5.addWidget(self.line_2)
        self.url_val = QtWidgets.QLineEdit(self.Setting)
        self.url_val.setMinimumSize(QtCore.QSize(30, 0))
        self.url_val.setStyleSheet("QLineEdit {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"    border: 1px solid rgb(255,255,255);\n"
"    border-radius: 5px;      /* (선택 사항) 모서리를 둥글게 */\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.url_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.url_val.setObjectName("url_val")
        self.horizontalLayout_5.addWidget(self.url_val)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.url_num_slider = QtWidgets.QSlider(self.Setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url_num_slider.sizePolicy().hasHeightForWidth())
        self.url_num_slider.setSizePolicy(sizePolicy)
        self.url_num_slider.setStyleSheet("QSlider::handle:horizontal{\n"
"    background: rgb(166, 217, 171);\n"
"    width: 20px;\n"
"    margin: -5px 0;\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"    background: rgb(100,170,100);\n"
"}\n"
"QSlider::handle:horizontal:pressed{\n"
"    background: rgb(50,120,50);\n"
"}")
        self.url_num_slider.setMinimum(1)
        self.url_num_slider.setMaximum(100)
        self.url_num_slider.setSingleStep(1)
        self.url_num_slider.setProperty("value", 1)
        self.url_num_slider.setOrientation(QtCore.Qt.Horizontal)
        self.url_num_slider.setObjectName("url_num_slider")
        self.verticalLayout_2.addWidget(self.url_num_slider)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.Setting)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.selected_engine = QtWidgets.QLabel(self.Setting)
        self.selected_engine.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.selected_engine.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.selected_engine.setObjectName("selected_engine")
        self.horizontalLayout_3.addWidget(self.selected_engine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.google_btn = QtWidgets.QRadioButton(self.Setting)
        self.google_btn.setStyleSheet("QRadioButton{\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.google_btn.setObjectName("google_btn")
        self.verticalLayout_2.addWidget(self.google_btn)
        self.naver_btn = QtWidgets.QRadioButton(self.Setting)
        self.naver_btn.setStyleSheet("QRadioButton{\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.naver_btn.setObjectName("naver_btn")
        self.verticalLayout_2.addWidget(self.naver_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.Setting, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1160, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Setting = QtWidgets.QMenu(self.menubar)
        self.menu_Setting.setObjectName("menu_Setting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menu_Setting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.send_btn.clicked.connect(self.input_txt.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.send_btn, self.input_txt)
        MainWindow.setTabOrder(self.input_txt, self.research_txt)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Research Results"))
        self.input_txt.setPlaceholderText(_translate("MainWindow", "Enter your message..."))
        self.send_btn.setText(_translate("MainWindow", "send"))
        self.label_3.setText(_translate("MainWindow", "Api-key"))
        self.api_key_txt.setPlaceholderText(_translate("MainWindow", "Enter your api key..."))
        self.label_5.setText(_translate("MainWindow", "Query number(1~100)"))
        self.query_val.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "url number(1~100)"))
        self.url_val.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Search Engine"))
        self.selected_engine.setText(_translate("MainWindow", "apply_Engine"))
        self.google_btn.setText(_translate("MainWindow", "Google"))
        self.naver_btn.setText(_translate("MainWindow", "Naver"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Setting), _translate("MainWindow", "setting"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu_Setting.setTitle(_translate("MainWindow", "&Setting"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
