# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#추가되는 include
from PlainTextEdit import mPlainTextEdit

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 475)
        MainWindow.setMinimumSize(QtCore.QSize(732, 475))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: rgb(20, 20, 20); /* 원하는 색상으로 변경 */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        #self.input_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input_text = mPlainTextEdit(self.centralwidget)
        self.input_text.setGeometry(QtCore.QRect(10, 350, 321, 31))
        self.input_text.setStyleSheet("QPlainTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.input_text.setPlainText("")
        self.input_text.setObjectName("input_text")
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setGeometry(QtCore.QRect(340, 350, 81, 31))
        self.send_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.send_btn.setObjectName("send_btn")
        self.history_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.history_txt.setGeometry(QtCore.QRect(220, 40, 201, 301))
        self.history_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.history_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.history_txt.setReadOnly(True)
        self.history_txt.setObjectName("history_txt")
        self.vertical_line = QtWidgets.QFrame(self.centralwidget)
        self.vertical_line.setGeometry(QtCore.QRect(440, 30, 1, 350))
        self.vertical_line.setStyleSheet("QFrame#vertical_line {\n"
"    background-color: white; /* 선 색깔을 배경색으로 설정 */\n"
"    border: none;            /* 기본 테두리 제거 */\n"
"    width: 1px;              /* 선의 굵기 (width) */\n"
"    /* 높이는 레이아웃에 따라 자동으로 조절되거나 명시적으로 지정 */\n"
"}")
        self.vertical_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.vertical_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vertical_line.setObjectName("vertical_line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 20, 50, 16))
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 70, 16))
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.api_key_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.api_key_txt.setGeometry(QtCore.QRect(460, 50, 241, 41))
        self.api_key_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.api_key_txt.setObjectName("api_key_txt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 30, 56, 16))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 110, 56, 16))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.prompt_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.prompt_txt.setGeometry(QtCore.QRect(460, 130, 241, 41))
        self.prompt_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.prompt_txt.setObjectName("prompt_txt")
        self.non_history_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.non_history_txt.setGeometry(QtCore.QRect(10, 40, 201, 301))
        self.non_history_txt.setStyleSheet("QTextEdit {\n"
"    color: white;\n"
"    background-color: rgb(40, 40, 40); /* 원하는 색상으로 변경 */\n"
"}\n"
"QTextEdit:focus {\n"
"    border: 1px solid rgb(184, 247, 185);\n"
"    outline: none;           /* 기본 포커스 아웃라인 제거 */\n"
"}")
        self.non_history_txt.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.non_history_txt.setReadOnly(True)
        self.non_history_txt.setObjectName("non_history_txt")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(460, 190, 81, 16))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: rgb(166, 217, 171);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.temp_combo = QtWidgets.QComboBox(self.centralwidget)
        self.temp_combo.setGeometry(QtCore.QRect(460, 210, 241, 22))
        self.temp_combo.setStyleSheet("QComboBox {\n"
"    color: white;\n"
"    background-color: rgb(40,40,40);\n"
"    border: 1px solid white; /* 2px 두께의 흰색 실선 테두리 */\n"
"    border-radius: 3px;      /* (선택 사항) 모서리를 둥글게 */\n"
"    padding: 1px 18px 1px 3px; /* 텍스트와 드롭다운 버튼을 위한 패딩 */\n"
"    min-width: 6em;          /* (선택 사항) 최소 너비 설정 */\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: white; /* 항목 텍스트 색상을 흰색으로 설정 */\n"
"    background-color: #333333; /* 드롭다운 목록 배경색 (잘 보이도록 어둡게) */\n"
"    selection-background-color: #558855; /* 항목 선택 시 배경색 */\n"
"    selection-color: white; /* 선택된 항목의 글씨색 (흰색으로 유지) */\n"
"    border: 1px solid white; /* 드롭다운 목록 테두리 (선택 사항) */\n"
"}")
        self.temp_combo.setObjectName("comboBox")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.temp_combo.addItem("")
        self.apply_btn = QtWidgets.QPushButton(self.centralwidget)
        self.apply_btn.setGeometry(QtCore.QRect(620, 350, 81, 31))
        self.apply_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(184, 247, 185);\n"
"    border: 1px solid rgb(184, 247, 185); /* 원하는 RGB 색상으로 변경 */\n"
"    border-radius: 5px;                  /* 모서리를 둥글게 (선택 사항) */\n"
"}\n"
"QPushButton:hover {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(50, 120, 50); /* 마우스 올렸을 때 더 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(184, 247, 185);\n"
"    background-color: rgb(100, 180, 100); /* 버튼 눌렀을 때 가장 진한 색 */\n"
"    border: 1px solid rgb(184, 247, 185); /* 테두리도 함께 진하게 (선택 사항) */\n"
"}")
        self.apply_btn.setObjectName("apply_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 21))
        self.menubar.setObjectName("menubar")
        self.menu_Setting = QtWidgets.QMenu(self.menubar)
        self.menu_Setting.setObjectName("menu_Setting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_Setting.menuAction())

        self.retranslateUi(MainWindow)
        self.send_btn.clicked.connect(self.input_text.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.input_text, self.send_btn)
        MainWindow.setTabOrder(self.send_btn, self.history_txt)

        #추가되는 코드
        self.input_text.set_send_button(self.send_btn)
        self.input_text.setPlaceholderText("Enter your message...")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_btn.setText(_translate("MainWindow", "send"))
        self.label.setText(_translate("MainWindow", "Default"))
        self.label_2.setText(_translate("MainWindow", "Experiment"))
        self.label_3.setText(_translate("MainWindow", "Api-key"))
        self.label_4.setText(_translate("MainWindow", "Prompt"))
        self.label_5.setText(_translate("MainWindow", "Temperature"))
        self.temp_combo.setItemText(0, _translate("MainWindow", "0.1"))
        self.temp_combo.setItemText(1, _translate("MainWindow", "0.2"))
        self.temp_combo.setItemText(2, _translate("MainWindow", "0.3"))
        self.temp_combo.setItemText(3, _translate("MainWindow", "0.4"))
        self.temp_combo.setItemText(4, _translate("MainWindow", "0.5"))
        self.temp_combo.setItemText(5, _translate("MainWindow", "0.6"))
        self.temp_combo.setItemText(6, _translate("MainWindow", "0.7"))
        self.temp_combo.setItemText(7, _translate("MainWindow", "0.8"))
        self.temp_combo.setItemText(8, _translate("MainWindow", "0.9"))
        self.temp_combo.setItemText(9, _translate("MainWindow", "1.0"))
        self.apply_btn.setText(_translate("MainWindow", "apply"))
        self.menu_Setting.setTitle(_translate("MainWindow", "&Setting"))
