# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#추가한 코드
from PyQt5.QtWidgets import QDialog, QDialogButtonBox, QTextEdit, QVBoxLayout, QLabel
from PyQt5.QtCore import pyqtSignal

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(428, 225)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.api_text = QtWidgets.QTextEdit(Dialog)
        self.api_text.setObjectName("api_text")
        self.gridLayout.addWidget(self.api_text, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.temp_val = QtWidgets.QComboBox(Dialog)
        self.temp_val.setObjectName("temp_val")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.temp_val.addItem("")
        self.gridLayout.addWidget(self.temp_val, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.prompt_text = QtWidgets.QTextEdit(Dialog)
        self.prompt_text.setObjectName("prompt_text")
        self.gridLayout.addWidget(self.prompt_text, 2, 1, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(643, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        #self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        #self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "api key :"))
        self.label_2.setText(_translate("Dialog", "temperature :"))
        self.temp_val.setItemText(0, _translate("Dialog", "0.1"))
        self.temp_val.setItemText(1, _translate("Dialog", "0.2"))
        self.temp_val.setItemText(2, _translate("Dialog", "0.3"))
        self.temp_val.setItemText(3, _translate("Dialog", "0.4"))
        self.temp_val.setItemText(4, _translate("Dialog", "0.5"))
        self.temp_val.setItemText(5, _translate("Dialog", "0.6"))
        self.temp_val.setItemText(6, _translate("Dialog", "0.7"))
        self.temp_val.setItemText(7, _translate("Dialog", "0.8"))
        self.temp_val.setItemText(8, _translate("Dialog", "0.9"))
        self.temp_val.setItemText(9, _translate("Dialog", "1.0"))
        self.label_3.setText(_translate("Dialog", "prompt :"))

class Settting_Dialog(QDialog):
    set_values = pyqtSignal(str, str, str)


    def __init__(self, parent = None):
        super().__init__(parent)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

        self.ui.buttonBox.accepted.connect(self._on_ok_button_clicked)
        self.ui.buttonBox.rejected.connect(self.reject)

    def _on_ok_button_clicked(self):
        api_key = self.ui.api_text.toPlainText().strip()
        temp = self.ui.temp_val.currentText()
        prompt = self.ui.prompt_text.toPlainText().strip()

        self.set_values.emit(api_key, temp, prompt)

        self.accept()

    def get_api_key(self):
        return self.ui.api_text.toPlainText()
    
    def set_api_key(self, key):
        self.ui.api_text.setPlainText(key)

    def get_temperature(self):
        return self.ui.temp_val.currentText()
    
    def set_temperature(self, key):
        self.ui.temp_val.setCurrentText()

    def get_prompt(self):
        return self.ui.prompt_text.toPlainText()
    
    def set_prompt(self, key):
        self.ui.prompt_text.setPlainText(key)